- type: job
  id: ESQuartermaster
  name: ESjob-name-quartermaster
  description: ESjob-description-quartermaster
  playTimeTracker: ESJobQuartermaster
  startingGear: ESQuartermasterGear
  icon: "JobIconCargoTechnician" # this is intentional, the upstream qm icon is just this but command-colored which we dont want
  access:
  - Cargo
  - Maintenance
  extendedAccess:
  - Salvage

- type: startingGear
  id: ESQuartermasterGear
  equipment:
    shoes: ClothingShoesColorBlack
    id: CargoPDA
    ears: ClothingHeadsetCargo
    head: ClothingHeadHatCargosoft
    jumpsuit: ClothingUniformJumpsuitCargo
    back: ClothingBackpack
  storage:
    back:
    - ESBoxSurvival

- type: chameleonOutfit
  id: ESQuartermaster
  job: ESQuartermaster
  hidden: false
