- type: entity
  id: ESBaseStationArrivals
  abstract: true
  components:
  - type: ESStationArrivals

- type: entity
  id: ESBaseStationEvacuation
  abstract: true
  components:
  - type: ESEvacStation
  - type: StationEmergencyShuttle

- type: entity
  id: ESBaseStationStoreroom
  abstract: true
  components:
  - type: ESStoreroomStation
  - type: ESCargoRequestStation

- type: entity
  id: ESBaseStationTelesci
  abstract: true
  components:
  - type: ESTelesciStation
    stages:
    - announcement: es-telesci-announcement-stage-1
      announcementSound:
        path: /Audio/_ES/Announcements/attention_high.ogg
        params:
          volume: -4
      events:
        id: ESPortalEventAnomalies
        amount: 3
    - announcement: es-telesci-announcement-stage-2
      announcementSound:
        path: /Audio/_ES/Announcements/attention_high.ogg
        params:
          volume: -4
      events:
        id: ESPortalEventAnomalies
        amount: 4
    - announcement: es-telesci-announcement-stage-3
      announcementSound:
        path: /Audio/_ES/Announcements/attention_high.ogg
        params:
          volume: -4
      events:
        id: ESPortalEventAnomalies
        amount: 5
    - announcement: es-telesci-announcement-stage-4
      announcementSound:
        path: /Audio/_ES/Announcements/attention_high.ogg
        params:
          volume: -4

- type: entity
  id: ESBaseStationNeutral
  parent:
  - BaseStation
  - BaseStationNews
  - BaseStationCargo
  - BaseStationJobsSpawning
  - BaseStationRecords
  - BaseStationAlertLevels
  - BaseStationAllEventsEligible
  - BaseStationDeliveries
  - ESBaseStationArrivals
  - ESBaseStationStoreroom
  - ESBaseStationTelesci
  categories: [ HideSpawnMenu ]
  components:
  - type: Transform
  - type: ESProducer
